aws:
  s3:
    bucket-name: file-process-bucket-fiap
  ses:
    sender: fiapvideosystem@gmail.com

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fiapvideosystem@gmail.com
    password: ${GMAIL_APP_PASSWORD:vdjccbriqrhwrnro}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  rabbitmq:
    addresses: amqps://rgovhbyf:PleWWS7G5pTsj7faqls2gI_B0HF72o36@seal.lmq.cloudamqp.com/rgovhbyf
    listener:
      simple:
        acknowledge-mode: auto

rabbitmq:
  queue:
    upload: fila.upload
