name: Pipeline CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Integration
    runs-on: ubuntu-latest

    env:
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuration
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build
        run:  ./gradlew clean build -x test

      - name: Unit tests
        run: ./gradlew test